# Generated by Django 2.1 on 2019-09-17 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipeDeApoio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.IntegerField(verbose_name='Número de telefone da Equipe de Apoio')),
            ],
        ),
        migrations.CreateModel(
            name='InvestigadorPrincipal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.IntegerField(verbose_name='Número de telefone do investigador')),
            ],
        ),
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_termino', models.DateField(verbose_name='Data de Término da Pesquisa')),
                ('investigador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SP_API.InvestigadorPrincipal')),
            ],
        ),
    ]
