# Generated by Django 2.1 on 2019-09-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SP_API', '0002_auto_20190920_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisa',
            name='data_termino',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Término da Pesquisa'),
        ),
    ]
