# Generated by Django 2.1 on 2019-10-04 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SP_API', '0004_auto_20190920_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaFinanceira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nota_fiscal', models.CharField(default=1, max_length=50, verbose_name='Número da nota fiscal')),
                ('data', models.DateField(auto_now=True, verbose_name='Data de entrada da nota')),
                ('descricao', models.CharField(default='Sem descrição', max_length=50, verbose_name='Descrição da entrada financeira')),
                ('valor', models.FloatField(default=0, verbose_name='Valor da entrada financeira')),
                ('status', models.CharField(choices=[('EM', 'Emitida'), ('SE', 'Solicitada e aguardando emissão'), ('CA', 'Cancelada')], default='EM', max_length=2, verbose_name='Status da entrada financeira')),
            ],
        ),
        migrations.CreateModel(
            name='SaidaFinanceira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recebedor', models.CharField(default='Nenhum recebedor cadastrado', max_length=30, verbose_name='Nome do recebedor')),
                ('numero_nota_fiscal', models.CharField(default=1, max_length=50, verbose_name='Número da nota fiscal')),
                ('data', models.DateField(auto_now=True, verbose_name='Data de saída da nota')),
                ('descricao', models.CharField(default='Sem descrição', max_length=50, verbose_name='Descrição da saída financeira')),
                ('valor', models.FloatField(default=0, verbose_name='Valor da saída financeira')),
                ('status', models.CharField(choices=[('EM', 'Emitida'), ('SE', 'Solicitada e aguardando emissão'), ('CA', 'Cancelada')], default='EM', max_length=2, verbose_name='Status da saída financeira')),
            ],
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='equipe_de_apoio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SP_API.EquipeDeApoio'),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='investigador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SP_API.InvestigadorPrincipal'),
        ),
        migrations.AddField(
            model_name='saidafinanceira',
            name='pesquisa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SP_API.Pesquisa'),
        ),
        migrations.AddField(
            model_name='entradafinanceira',
            name='pesquisa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SP_API.Pesquisa'),
        ),
    ]
