# Generated by Django 2.1 on 2019-11-01 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SP_API', '0005_auto_20191004_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Sem nome disponível', max_length=30, verbose_name='Nome do paciente')),
                ('cpf', models.BigIntegerField(default='12345678909', verbose_name='Cpf do paciente')),
                ('telefone', models.CharField(default='31999999999', max_length=20, verbose_name='Número de celular do paciente')),
            ],
        ),
        migrations.AlterField(
            model_name='entradafinanceira',
            name='pesquisa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='SP_API.Pesquisa'),
        ),
        migrations.AlterField(
            model_name='saidafinanceira',
            name='pesquisa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='SP_API.Pesquisa'),
        ),
    ]
