# Generated by Django 2.1 on 2019-11-01 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SP_API', '0006_auto_20191101_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='pesquisa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='SP_API.Pesquisa'),
        ),
    ]
