# Generated by Django 2.1 on 2019-11-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SP_API', '0007_paciente_pesquisa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipedeapoio',
            name='email',
            field=models.CharField(default='exemplo@gmail.com', max_length=50, verbose_name='Email da Equipe de Apoio'),
        ),
        migrations.AlterField(
            model_name='equipedeapoio',
            name='nome_da_coordenacao',
            field=models.CharField(default='Exemplo', max_length=50, verbose_name='Nome da Coordenação'),
        ),
        migrations.AlterField(
            model_name='investigadorprincipal',
            name='email',
            field=models.CharField(default='exemplo@gmai.com', max_length=50, verbose_name='Email do investigador'),
        ),
        migrations.AlterField(
            model_name='investigadorprincipal',
            name='nome',
            field=models.CharField(default='Fulano', max_length=50, verbose_name='Nome do Investigador'),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='numero_CAAE',
            field=models.CharField(default='123', max_length=50, verbose_name='Numero da Plataforma Brasil'),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='patrocinadores',
            field=models.CharField(default='Exemplo', max_length=50, verbose_name='Patrocinadores da Pesquisa'),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='setor_de_atuacao',
            field=models.CharField(default='Exemplo', max_length=50, verbose_name='Setor de atuação da Pesquisa'),
        ),
    ]
