# Generated by Django 2.1 on 2019-11-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SP_API', '0008_auto_20191118_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisa',
            name='titulo',
            field=models.CharField(default='Exemplo', max_length=80, verbose_name='Título da Pesquisa'),
        ),
    ]
