# Generated by Django 2.1 on 2019-11-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SP_API', '0009_auto_20191118_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipedeapoio',
            name='telefone',
            field=models.CharField(max_length=50, verbose_name='Número de telefone da Equipe de Apoio'),
        ),
        migrations.AlterField(
            model_name='investigadorprincipal',
            name='telefone',
            field=models.CharField(max_length=50, verbose_name='Número de telefone do investigador'),
        ),
    ]
