# Generated by Django 2.1 on 2019-11-20 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SP_API', '0010_auto_20191118_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradafinanceira',
            name='pesquisa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='SP_API.Pesquisa'),
        ),
        migrations.AlterField(
            model_name='saidafinanceira',
            name='pesquisa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='SP_API.Pesquisa'),
        ),
    ]
